### ISSUE TITLE
Checklist das atividades do portfólio

### ISSUE THREAD

**Issue by anderdot** [anderdot/portfolio#5]
# Checklist das atividades do portfólio
## Planejamento
- [X] Encontrar inspirações
- [X] Definir sessões do portfólio
- [X] Definir paleta de cores
- [X] Definir fonte do projeto
- [X] Criar uma issue no projeto com a checklist
- [ ] Avaliar a criação de um Figma

## Cabeçalho
- [X] Criar uma nav responsiva e fixa no topo da página
- [X] Criar os links com cada sessão
- [x] Ajustar em telas menores

## Apresentação
- [X] Adicionar uma foto sempre fixa no final da página
- [X] Adicionar um título e um parágrafo com parte em negrito
- [x] Adicionar links de contato
- [ ] Criar texto da sessão
- [ ] Ajustar em telas menores e maiores

## Biografia
- [ ] Encontrar outro nome para essa sessão. 'quem sou', 'sobre'?
- [ ] Agrupar algumas imagens a direita que possa exemplificar
- [ ] Adicionar um título e dois parágrafos
- [ ] Criar texto da sessão
- [ ] Ajustar imagens no celular, para ficarem dos dois lados da tela, cortando
- [ ] Ajustar em telas menores e maiores

## Trajetória
- [ ] Construir uma timeline vertical, que possa ser clicado nos pontos para mostrar
- [ ] Adicionar um título e um parágrafo
- [ ] Deixar um espaço para uma imagem
- [ ] Criar texto da sessão
- [ ] Avaliar usar mais de uma sessão para isso
- [ ] Ajustar em telas menores e maiores

## Conhecimentos
- [ ] Separar por áreas (Banco de Dados, Back-end, Front-end)
- [ ] Adicionar um shield de cada tecnologia com breve descrição
- [ ] Criar texto da sessão
- [ ] Ajustar o layout para funcionar em telas menores
- [ ] Ajustar em telas menores e maiores

## Projetos
- [ ] Criar um carrossel de projetos
- [ ] Adicionar tags em cada um
- [ ] Criar breve descrição sobre eles
- [ ] Adicionar link direto do repositório e deploy
- [ ] Ajustar em telas menores e maiores

## Contato
- [ ] Adicionar uma sessão de envio de e-mail (caso possível)
- [ ] Adicionar um preview das outras redes e contatos
- [ ] "Vamos marcar um café para conversarmos"
- [ ] Ajustar em telas menores e maiores

## Rodapé
- [ ] Feito com ❤
- [ ] Todos os direito reservados
- [ ] Ajustar em telas menores

# Fase 1

- [ ] Tudo acima concluído
- [ ] Fase 1 do projeto terminada

# Blog
_Em breve_

# Textos dinâmicos em diversos idiomas
_Em breve_
